repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks-docker
  - repo: https://github.com/astro/deadnix
    rev: v1.2.1
    hooks:
      - id: deadnix
        stages: [pre-commit]
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.1.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/fidgetingbits/pre-commit-statix
    rev: v1.0.0
    hooks:
      - id: statix-fix
      - id: statix-check
