keys:
  # Users
  - &users:
    - &wcarlsen 657467314A9A4BF05871C2BE983F48E12A6B265E
  # Hosts
  - &hosts:
    - &nixos-x1 age1pm90w8fw73q6znkz82zamt3wmjkyctm2wggy4nmsf66ntruvgu8qtj6m5m

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - pgp:
          - *wcarlsen
        age:
          - *nixos-x1