{
  imports = [
    ./atuin.nix
    ./aws.nix
    ./bat.nix
    ./carapace.nix
    ./direnv.nix
    ./eza.nix
    ./gcp.nix
    ./git.nix
    ./hunk.nix
    ./jujutsu.nix
    ./kubernetes.nix
    ./misc.nix
    ./pay-respects.nix
    ./pi.nix
    ./television.nix
    ./worktrunk.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
