# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-0f18d868-d471-4114-a84a-32b9515672d8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0f18d868-d471-4114-a84a-32b9515672d8".device = "/dev/disk/by-uuid/0f18d868-d471-4114-a84a-32b9515672d8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1FC0-A2F6";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-665d1485-263f-4f32-b8d0-cbaaea7b6e0d";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
